### ISSUE TITLE
Add static vessel parameter/data management

### ISSUE THREAD

**Issue by ri0t** [Hackerfleet/hfos#10]
<a href="https://github.com/ri0t"><img src="https://avatars.githubusercontent.com/u/1938065?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ri0t](https://github.com/ri0t)**
_Sunday Aug 17, 2014 at 14:50 GMT_
_Originally opened as https://github.com/Hackerfleet/hfos_old/issues/10_

----

Needs 
* [x] Schema for vessel parameters
* [x] a configuration form to input vessel data 
 * [x] Controller or even a simple jsonschemaform dialog

**Comment by ij0n** [comment]
Vessel static parameter

LOA
LWL
Beam
Draft (not so static! change should  be possible for each voyage)
Height Minimum (think of ships that can change the height)
Height Maximum 
Number of propulsion Engines
Number of (Sail) Masts / Kites / Wings
Waterproduction capacity
Waterstoring capacity
Fuel storing capacity

maybe information about the amount of cabins/bunks

**Comment by ri0t** [comment]
I've added these to the new Vesselobject type. I'm a little reluctant to build yet another non-generic object editor, though, so i'm trying to put up a generic one now (we need this anyway for the dozens of other object types coming in)
