### ISSUE TITLE
Geocoding mit geohack

### ISSUE THREAD

**Issue by ij0n** [Hackerfleet/hfos#178]
Beispiel wie eine Position ausgedrückt werden könnte: https://tools.wmflabs.org/geohack/geohack.php?language=nl&params=52_17_28_N_5_32_32_E_type:waterbody_scale:25000&pagename=Nuldernauw

**Comment by ri0t** [comment]
Soll da einfach nur nen link auf die geohack seite mit der angeklickten koordinate ins popup menü??

**Comment by ri0t** [comment]
Erledigt ;)
