### ISSUE TITLE
Create Autodiscovery for NMEA Data

### ISSUE THREAD

**Issue by ij0n** [Hackerfleet/hfos#239]
There might be more then one EPFS (electronic position fixing system) on the Bus. 
in Regards of heading/course, there might be a Gyro and a magnetic compass, or several of them
also both Radars may deliver ARPA-Data over the bus.

the system needs a way to scan all com-ports on the node for data and compile a report what kind of data on which port data arrives. the system needs in the case of nmea0183 experiment with different baud-rates, starting from 9600, then trying 4800 and then other inter multiples of 4800

the system needs to tell the user which com-ports it could reserve for reading, and which com-ports were not possible to reserve.

also the system needs to create a very detailled report about errors and problems with all the bus-components - during development there should in this module especially a focus on error messages

**Comment by ri0t** [comment]
Would it make sense to have this scanner available as a button in the nmea parser's component configuration GUI? That way, only admins can access it (makes sense), it doesn't clutter the interface and the process can easily be started. 

Also, I'll probably move the gdal-map rescan button to the gdal component's configuration as well, so i'd have two usecases for implementing a button functionality in the  configurator already - and more come to mind)

**Comment by ri0t** [comment]
The system now autoconfigures nmea serial ports, if autoconfiguration for nmea is activated and not already configured. Basics = Done.
What it still needs for the future:
* Better protocol detection (right now you need a GPS attached!)
* Feedback if it finds more than one possible bus
* Manual triggering of scans
