### ISSUE TITLE
use chat for debug outputs

### ISSUE THREAD

**Issue by ij0n** [Hackerfleet/hfos#242]
especially when debugging NMEA it is useful to have a debug-output on the clients.

I thought we could have a local chatroom with all NMEA-messages pasted to it, when activated.

also we could have all other kind of debug-messages that might be relevant to the crew in a second chatroom. that way we neatly keep it all mobile and usable.

**Comment by ri0t** [comment]
Nah. Abusing the chat for such stuff is not really helpful. I'm extending the system logging, so admins can actually check out what is going on - that way, they'll automatically get far more clarity on what is generally going on. In future, to accomplish the above, you just go to the system log and filter for nmea, while you have that module in "debug" mode - so it actually logs those incoming messages to the system log - which in normal operation it shouldn't do anyway!
