### ISSUE TITLE
Add non-JS based user registration (just for LAC, now)

### ISSUE THREAD

**Issue by ri0t** [Hackerfleet/hfos#301]
This is just for the LAC18 participant registration (for the users with strong javascript aversions) but might as well be a proving ground for #164 (Hello, @x42 ;D)

**Comment by x42** [comment]
Can the form be customized per conference?

ie. for LAC it'd be great to have a "Are you interested to buy printed proceedings (~20 euro)?"
compare to https://github.com/x42/lac2015/blob/master/pages/registration.php#L400

**Comment by x42** [comment]
PS. previously we made sure the site is also accessible (Screen-reader, braille reader). There are volunteers on the Linux-Audio-User ML to verify this.

**Comment by ri0t** [comment]
That'll be another issue. Gotta update the profile object for LAC -> #303
