### ISSUE TITLE
Clean packaging of subcomponents

### ISSUE THREAD

**Issue by ri0t** [Hackerfleet/hfos#52]
Hmm. Needs:
* [x] Installation meta
* [ ] Frontend bits
* [x] Backend bits
* [x] Data 
 * [x] Schemata
 * [x] Provisions

**Comment by ri0t** [comment]
We've done something in that direction with an earlier prototype. Might be worthwhile to check that out, but separating in the new frontend is another topic.

**Comment by prologic** [comment]
Have a look at a similar thing I've done [here](https://github.com/prologic/kdb/blob/master/kdb/plugins/web.py) admitedly it *coudl* be packaged up a bit better though!

**Comment by ri0t** [comment]
Still needs a bit fine tuning and a few minor pieces, but it generally works.
